// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

// Data reducer types
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const LIKE_PRODUCT = 'LIKE_PRODUCT';
export const UNLIKE_PRODUCT = 'UNLIKE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const SET_ORDERS = 'SET_ORDERS';
export const LOADING_ORDER = 'LOADING_ORDER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const SET_SPECIAL_OFFERS = 'SET_SPECIAL_OFFERS';
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS'; 
export const EMPTY_CART = 'EMPTY_CART';
export const PLACE_ORDER = 'PLACE_ORDER';
export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const CLEAR_CART = 'CLEAR_CART';
export const LOADING_PAYMENT = 'LOADING_PAYMENT';
export const SET_MEDICATION = 'SET_MEDICATION';
export const LOADING_MEDICATION = 'LOADING_MEDICATION';
export const SET_SINGLE_MEDICATION = 'SET_SINGLE_MEDICATION';



export const TAKE_MEDICATION = 'TAKE_MEDICATION';
export const CANCEL_MEDICATION = 'CANCEL_MEDICATION';



